version: 2
jobs:
  test:
    docker:
      - image: semgrep/semgrep
    parameters:
      folder:
        type: string
    steps:
      - checkout
      - run:
          name: Set permissions
          command: chmod +x .circleci/base_config/semgrep.sh
      - run:
          name: "Semgrep scan"
          command: |
              .circleci/base_config/semgrep.sh
workflows:
  version: 2
  dynamic:
    jobs:
      - call:
          job: test
          parameters:
            folder: "serviceA"
