version: 2.1

orbs:
  maven: circleci/maven@1.2.0

parameters:
  run-build-service-A-job:
    type: boolean
    default: false
  run-build-service-B-job:
    type: boolean
    default: false

workflows:
  service-A:
    when: << pipeline.parameters.run-build-service-A-job >>
    jobs:
      semgrep:
        docker:
          - image: semgrep/semgrep
        steps:
          - checkout
          - run:
              name: Set permissions
              command: chmod +x .circleci/base_config/semgrep.sh
          - run:
              name: "Semgrep pull request scan"
              app_src_directory: 'serviceA'
              command: |
                  .circleci/base_config/semgrep.sh
  service-B:
    when: << pipeline.parameters.run-build-service-B-job >>
    jobs:
      semgrep:
        docker:
          - image: semgrep/semgrep
        steps:
          - checkout
          - run:
              name: Set permissions
              command: chmod +x .circleci/base_config/semgrep.sh
          - run:
              name: "Semgrep pull request scan"
              app_src_directory: 'serviceA'
              command: |
                  .circleci/base_config/semgrep.sh
