version: 2.1

orbs:
  maven: circleci/maven@1.2.0

parameters:
  service:
    type: string
    default: "A"

workflows:
  service-semgrep:
    when: << pipeline.parameters.service  == "A" >>
    jobs:
      semgrep:
        docker:
          - image: semgrep/semgrep
        steps:
          - checkout
          - run:
              name: Set permissions
              command: chmod +x .circleci/base_config/semgrep.sh
          - run:
              name: "Semgrep pull request scan"
              app_src_directory: 'serviceA'
              command: |
                  .circleci/base_config/semgrep.sh
              app_src_directory: 'packages/serviceA'
              command: |
                  .circleci/base_config/semgrep.sh
